### ISSUE TITLE
Passing in `-language-version` to `kotlincArguments` fails to parse

### ISSUE THREAD

**Issue by ZacSweers** [tschuchortdev/kotlin-compile-testing#196]
```kotlin
KotlinCompilation()
  .apply {
    // ...
    kotlincArguments = listOf("-language-version 1.5.30")
  }
```

Results in a surprising failure like this when compilation is run

```
java.lang.IllegalArgumentException: Errors parsing kotlinc CLI arguments:
Invalid argument: -language-version 1.5.30
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.commonArguments(AbstractKotlinCompilation.kt:142)
	at com.tschuchort.compiletesting.KotlinCompilation.commonK2JVMArgs(KotlinCompilation.kt:293)
	at com.tschuchort.compiletesting.KotlinCompilation.stubsAndApt(KotlinCompilation.kt:453)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:636)
```

which has me wondering if KCT should be `validateArguments` vs just letting kotlinc do its own validation internally anyway

**Comment by ZacSweers** [comment]
It's worth noting this fails with `1.5` as an input as well with the same error

**Comment by ZacSweers** [comment]
Example can be found in this PR: https://github.com/square/moshi/pull/1390

**Comment by tschuchortdev** [comment]
Are you sure kotlinc will validate the arguments again and do different validation? When we call `K2JVMCompiler` we are asked to pass an instance of `K2JVMCompilerArguments` and not string options so I suppose that they expect us to have already parsed and validated them.

**Comment by ZacSweers** [comment]
I am not sure where the validation is run, but I know the above syntax is correct and only fails in kotlin-compile-testing

**Comment by tschuchortdev** [comment]
I finally figured it out: if you are using space to delimit the option name from its value (which I dislike to do), then they are two separate arguments from the perspective of the command-line, thus they have to be two separate elements in the argument list:

```kotlincArguments = listOf("-language-version", "1.5")``` did work.

By all accounts, my preferred way `listOf("-language-version=1.5")` [should work too](https://github.com/JetBrains/kotlin/blob/e483b9b52b231167b04287be73bbf98e8e328cf4/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/parseCommandLineArguments.kt#L112). It turns out that it does not, due to a bug/inconsistency in the Kotlin CLI parser which [has already been fixed](https://github.com/JetBrains/kotlin/commit/5871f3d6637a578f9ef0250f87fe04c2b8f88c1b) but not included in the latest Kotlin release (will come in 1.6.0). This really tripped me up.

I will also include a new property in the next release so you can set `languageVersion` directly.
