### ISSUE TITLE
Incompatible with Kotlin 1.3.60

### ISSUE THREAD

**Issue by ZacSweers** [tschuchortdev/kotlin-compile-testing#30]
It appears that Kapt expects a no-arg constructor for `ComponentRegistrar` implementations

```
java.lang.NoSuchMethodError: org.jetbrains.kotlin.kapt3.Kapt3ComponentRegistrar$KaptComponentContributor: method <init>()V not found
        at com.tschuchort.compiletesting.KaptComponentRegistrar.registerProjectComponents(KaptComponentRegistrar.kt:97)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:594)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:133)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:173)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:420)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:263)

```

**Comment by ZacSweers** [comment]
Note - it's not announced publicly yet, but Kotlin 1.3.60 was released yesterday

**Comment by tschuchortdev** [comment]
How did you even get this error? kotlin-compile-testing should always use the compiler-embeddable version that is declared in `build.gradle`.  Unless you updated the compiler-embeddable version in your fork and then ran into this problem.

Also, since the newest version the compiler should no longer try to instantiate `Kapt3ComponentRegsitrar` itself. That's now handled by `MainComponentRegistrar`, which has a no-arg constructor. 

It seems to be the  `KaptComponentContributor` that is missing a no-arg constructor.

**Comment by ZacSweers** [comment]
Here's a repro case: https://github.com/square/moshi/pull/1024. Pretty standard setup.

**Comment by ZacSweers** [comment]
> should always use the compiler-embeddable version that is declared in build.gradle

Are you suggesting the library should use a mismatched version even if the consumer is using a newer version of the compiler...?

**Comment by tschuchortdev** [comment]
What local compiler version the user has is not important as my library depends on the kotlin-compiler-embeddable. If your project also depends on a different version of kotlin-compiler-embeddable then you have a dependency conflict. Afaik this can hardly be avoided (if you know a way then please tell me). So you have 2 options really:

- Overwrite the transitive dependency pulled in through the kotlin-compile-testing dependency with your own and hope that it works

- Use the same version of kotlin-compiler-embeddable as used by kotlin-compile-testing and wait until a new release comes out with an updated kotlin-compiler-embeddable dependency.   

Unfortunately kotlin-compile-testing can only ever support one kotlin-compiler-embeddable version at a time because the private APIs we are using are constantly evolving and that can not be changed.

**Comment by ZacSweers** [comment]
> Unfortunately kotlin-compile-testing can only ever support one kotlin-compiler-embeddable version at a time because the private APIs we are using are constantly evolving and that can not be changed.

Yes, that's why I opened a PR 🙂

**Comment by tschuchortdev** [comment]
Perhaps it would make sense to copy all the code of the kapt plugin to the library instead of depending on the compiler-embeddable's kapt classes. That should avoid a lot of the problems when a user (unknowingly) overwrites the kotlin-compiler-embeddable transitive dependency. But it also incurs a significant maintainance cost if the kapt semantics or public interface ever change.

**Comment by ZacSweers** [comment]
That sounds pretty tedious to maintain :/. I think supporting a minimum version is fine. My 2c is still that a library that uses private/unstable APIs shouldn't really be using major semver versions, but that's out of scope of this.

**Comment by ZacSweers** [comment]
This appears to still be broken in 1.2.5 :/ 

```
e: java.lang.NoSuchMethodError: org.jetbrains.kotlin.kapt3.Kapt3ComponentRegistrar$KaptComponentContributor.<init>(Lorg/jetbrains/kotlin/resolve/jvm/extensions/PartialAnalysisHandlerExtension;)V
	at com.tschuchort.compiletesting.KaptComponentRegistrar.registerProjectComponents(KaptComponentRegistrar.kt:102)
	at com.tschuchort.compiletesting.MainComponentRegistrar.registerProjectComponents(MainComponentRegistrar.kt:42)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:631)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:145)
```

**Comment by tschuchortdev** [comment]
That's weird. I will look into it.

**Comment by tschuchortdev** [comment]
I don't see what the problem is. I checked out your moshi PR https://github.com/square/moshi/pull/1024 and tried the offending tests locally with kct 1.2.5 and it worked. Or did this new error appear somewhere else? It looks like you are now using kct 1.2.5 with a pre-1.3.60 compiler-embeddable :confused:

**Comment by ZacSweers** [comment]
That's not the right PR to check, there is another one open for updating this dependency first. https://github.com/square/moshi/pull/1014

**Comment by tschuchortdev** [comment]
You can't update either one first. The versions of `kotlin-compiler-embeddable` have to agree, so you can only update them together.

In the PR that you linked the kotlin version of moshi is still 1.3.50: https://github.com/square/moshi/blob/1fed6e2c85da19e639bd9215a966f6db02ec98f6/pom.xml#L39

If you change that to 1.3.60 as well it works
