### ISSUE TITLE
Failing tests (especially for annotation processor)

### ISSUE THREAD

**Issue by a11n** [tschuchortdev/kotlin-compile-testing#4]
Great library! I tried to use it for testing my annotation processor, but the processor never got called. So I cloned this repo and executed the tests to see what's wrong.

Unfortunately there are 9 failings tests after a clean checkout:
- Java AP sees Java class
- Kotlin can access generated Kotlin class
- Java AP sees Kotlin class
- Kotlin AP sees Java class
- Java can access generated Kotlin class
- Kotlin AP sees Kotlin class
- Kotlin can access generated Java class
- Java can access generated Java class
- Given only Java sources, Kotlin sources are generated and compiled

It seems the annotation processing isn't working.

Do you have any special setup?

I'm running the following configuration:

> IntelliJ IDEA 2019.1 (Community Edition)
> Build #IC-191.6183.87, built on March 27, 2019
> JRE: 11.0.2+9-b159.30 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.1
>jdk1.8.0_162

**Comment by a11n** [comment]
Cross checked on two other machines, the tests are running on a windows machine (with jdk1.8.0_212) but not on another MacOS tested with different JDKs. Very strange.

**Comment by tschuchortdev** [comment]
That's weird. Unfortunately I don't have a MacOS machine so I can only personally test on Windows and Linux. 

Can you post the output of the tests with the `verbose` option enabled? What are the options that you are calling the `KotlinCompilation` with? Did you also test with an OpenJDK?

Since you said that it works on Windows and still fails on MacOS with a different JDK, I'll assume that the problem is somehow related to MacOS in general. If we are lucky it could just be a problem with some path. This should be fairly easy to catch if you run one of the tests on Windows and MacOS in parallel and step through the `stubsAndApt` function. Make sure that discovery of the `toolsJar` works and the `resourcesPath` is correct. 

However, in the worst case this could be some internal weirdness of the compiler itself. It has many wards and hard to diagnose bugs that required several esoteric workarounds just to make it work as it is. 

Also note that the compiler version is a slightly older one. If you use any of the new features like inline classes it won't work. You can of course try updating the version yourself in the library's `build.gradle` file. I haven't yet done so myself because of the internal compiler bugs mentioned above that may break again. We aren't really meant to call the compiler like that directly so the Kotlin team doesn't pay any attention to keeping things compatible.

**Comment by tschuchortdev** [comment]
@a11n I have released a new version with a bug fix that should hopefully resolve your problem. Please see if it works now.

**Comment by a11n** [comment]
It works perfectly now! Thank you very much for the quick fix and your great work.
