### ISSUE TITLE
KSP errors are not included in the message output

### ISSUE THREAD

**Issue by ansman** [tschuchortdev/kotlin-compile-testing#69]
I'm trying to use errors printed by KSP in my test but it seems that any KSP logs are not included. I see them in the test logs but not in `KotlinCompilation.Result.messages`.

**Comment by evant** [comment]
It's because the stderror stream isn't captured. Was able to work around this by capturing the stderr stream myself. https://github.com/evant/kotlin-inject/blob/main/compiler-tests/src/main/kotlin/me/tatarka/inject/ProjectCompiler.kt#L31

**Comment by ZacSweers** [comment]
I've got a slightly different hack via just copying the sources (leftover from when I needed a newer version compatible with the new package names): https://github.com/ZacSweers/MoshiX/blob/main/ksp-test-util/src/main/kotlin/com/tschuchort/compiletesting/symbolProcessors.kt#L94-L98

@tschuchortdev do you have an implementation in mind for this TODO item in Ksp.kt?

https://github.com/tschuchortdev/kotlin-compile-testing/blob/master/ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt#L121

If so I'd be happy to take a look at a PR!

**Comment by tschuchortdev** [comment]
@ZacSweers I don't have a specific implementation in mind. The whole KSP implementation is kind of hacky, because kotlin-compile-testing is not very composable currently, so you might not find a "clean" way to access the `KotlinCompilation.messageOutputStream`. My plan is to gather complaints/use cases for now and then rewrite it (in December maybe) to be more composable when I have a better grasp of the requirements. Since this will break API compatibility I don't want to rush it and have to rewrite again in the future. 

I would try one of the following approaches:

- Maybe you can get the compiler's message collector from `MockProject` or `CompilerConfiguration` inside `ComponentRegistrar.registerProjectComponents`. Usually all `ComponentRegistrar`s should use the same `MessageCollector` that is given to `K2JVMCompiler` by the user, right? So there must be some way for a `ComponentRegistrar` to access the configured `MessageCollector`. I don't think they can receive it through the constructor because `ComponentRegistrar`s are often instantiated by a service locator. You can also look at the source code of KSP to see where they get it from.

- Somehow access the `KotlinCompilation.messageOutputStream` in a hacky way and replace it with something like `TeeOutputStream`. 

- Just add a parameter where the user can set the `OutputStream` to be used for KSP. This has the disadvantage that the messages still won't be recorded in the `Result` class.

**Comment by yigit** [comment]
Btw, this might be just related to https://github.com/google/ksp/issues/122.
KSP right now does not report errors to the compilation pipeline so once it is fixed, this issue "might" go away.

**Comment by tschuchortdev** [comment]
@yigit Originally it was simply the case that the KSP-related code had no access to the Outputstream where all the compiler messages are saved. Now that the KSP implementation has changed, deeper changes in KCT will be required to adapt and this issue should get fixed as well.
